public class homecontroller {

      public homecontroller()
      {
        //String url = 'https://login.salesforce.com/services/oauth2/authorize';
       /* HttpRequest request = new HttpRequest();

        String url = 'https://login.salesforce.com/services/oauth2/authorize?response_type=code&client_id='+'3MVG9CEn_O3jvv0zLoDC.MZAh38h1uf1lv1SgmMcF7QmdlhYTv0QSV3fb9TKOIuISJ2GnF6TiCTidgfmqSA6I'
        +'&redirect_uri=https://na50.salesforce.com/&state=mystate';


        
        request.setMethod('POST');  
        request.setendpoint(url);
        request.setBody('response_type=code');
        //request.setHeader('client_id','3MVG9CEn_O3jvv0zLoDC.MZAh38h1uf1lv1SgmMcF7QmdlhYTv0QSV3fb9TKOIuISJ2GnF6TiCTidgfmqSA6I');
        request.setBody('client_id=3MVG98SW_UPr.JFiTkbSUvxViBlNL98s8oFcgJuiHsLzRl4SQ_cY9KZ7N._aVL33tDF.5TKQrQbykh0uCF.UE');
         
        request.setBody('state=mystate');
        //request.setHeader('redirect_uri','https://na50.salesforce.com');
        request.setBody('redirect_uri=https://login.salesforce.com');
        Http  http= new Http();
        HTTPResponse response = http.send(request); 
        system.debug(request+'####################'+response);
        String resp = response.getBody();
        system.debug('####################'+resp);*/
        
      }
}